title: Michael Obeng | Data Analyst
description: Turning data into actionable insights
baseurl: "/analyst-portfolio" 
url: "https://obengmichael777-ctrl.github.io"
markdown: kramdown

collections:
  project_archive:
    output: true
    permalink: /projects/:path/
  project_brief_library:
    output: false
    
defaults:
  - scope:
      path: ""
      type: "project_archive"
    values:
      layout: project