title: Michael Obeng | Data Analyst
description: Turning data into actionable insights
baseurl: "/analyst-portfolio" 
url: "https://obengmichael777-ctrl.github.io"
markdown: kramdown
collections:
  projects:
    output: true
    permalink: /projects/:path/
